/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7/userguide/building_java_projects.html
 */

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  id("org.jetbrains.kotlin.jvm") version "1.4.10"
  id("com.github.johnrengelman.shadow") version "6.1.0"

  // Apply the java-library plugin for API and implementation separation.
  `java-library`
}

repositories {
  // Use JCenter for resolving dependencies.
  jcenter()
}

java {
  withSourcesJar()
}

dependencies {
  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use the Kotlin JDK 7 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2")

  // This dependency is used internally, and not exposed to consumers on their own compile classpath.
  implementation("com.google.guava:guava:29.0-jre")

  implementation("org.koin:koin-core:2.2.0")
  implementation("com.mashape.unirest:unirest-java:1.3.1")
  implementation("com.squareup.moshi:moshi-kotlin:1.9.3")
  implementation("com.squareup.moshi:moshi-kotlin-codegen:1.9.3")
  implementation("moe.banana:moshi-jsonapi:3.5.0")

  implementation("org.dmfs:lib-recur:0.11.5")
  implementation("org.ocpsoft.prettytime:prettytime:4.0.4.Final")


  // Use the Kotlin test library.
  testImplementation("org.jetbrains.kotlin:kotlin-test")

  // Use the Kotlin JUnit integration.
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

  testImplementation("junit:junit:4.12")
  testImplementation("org.robolectric:robolectric:4.2.1")

  // This dependency is exported to consumers, that is to say found on their compile classpath.
  api("org.apache.commons:commons-math3:3.6.1")
}
